### ISSUE TITLE
Need information on setting the Username and Password for Configured Thanos RemoteWrite Url

### ISSUE THREAD

**Issue by sagarramamoorthi1986** [open-fresh/avalanche#21]
Hi All,

I am using the below mentioned command for setting the configurations to send the data to thanos using remotewrite API.
 docker run -p 9001:9001 quay.io/freshtracks.io/avalanche  --metric-count=5 --label-count=2  --const-label=TenantId=tenant1 --const-label=ProductName=Pname  --remote-url=http://<RemoteWrite>/api/v1/receive

Need information on how to set the user name and password for the Thanos remote write URL to push the data to thanos.
When i checked the help options i dont see any option to set Username and Pwd .

**Comment by Eraac** [comment]
Can not be done using `https://<username>:<password>@<url>/<path>` format? Not the best but probably a good workaround

**Comment by Hammond95** [comment]
I don't know about thanos, but we successfully used avalanche to perform load testing from different tenants doing remote writes to cortex.

we used in our deployments to set container arguments something like this:

```YAML
      containers:
      - name: pg-avalanche
        image: avalanche-image-here
        args:
        - "--metric-count=15000"
        - "--series-count=4"
        - "--label-count=5"
        - "--port=9001"
        - "--series-interval=2629746"
        - "--metric-interval=2629746"
        - "--remote-url=https://cortex-distributor.***.****.**/api/prom/push"
        - "--remote-batch-size=1000"
        - "--const-label=orgid={{ .Values.orgId }}"
        - "--remote-requests-count=1000"
        - "--remote-write-interval=30s"
        - "--remote-tenant={{ .Values.orgId }}"
        - "--tls-client-insecure"
```
